### PR TITLE
[TECHNICAL REQUEST] 	AUI-2037 & AUI-2038 on 2.0.x

### PR DESCRIPTION
**Pull request by peterborkuti**
Hi Byrån,

Now it works with portal 62x.

Could you review it?

Is it good for an SDH?

Thank you in advance
Péter

### CODE REVIEW

**Comment by blzaugg** [comment]
I'm doing another backport using the majority of the commits you already used.

Everything looks good but I'm doing a little more testing to ensure I we covered everything. I expect to be done tomorrow.

**Comment by peterborkuti** [comment]
Thanks.

**Comment by alfonsocrisci** [comment]
Hi Byrån,

Are there updates regarding the backport?

Thanks,

Alfonso

**Comment by blzaugg** [comment]
Sorry, I was out yesterday. I'll wrap this up this afternoon.

**Comment by blzaugg** [comment]
https://github.com/peterborkuti/alloy-ui/pull/4

**Pull request closed without merging**
