### PR TITLE
[TECHNICAL SUPPORT] AUI-1953 Unable to have same 'value' for Select with different name/option

### PR DESCRIPTION
**Pull request by zsagia**
Hi Byran,

I'm forwarding to you Peter Borkuti's fix for AUI-1953.

"
Hi,

This is basically the same as my previous pull, but during the backport, I noticed, that it is easier to backport if I use 'label' and 'value' as the option attribute-names.

Plus I added a useful private method.

It may be usefule to add the next public methods:

createOption
getOptionValue(option)
getOptionLabel(option)

With these we could loosen the coupling between classes.
"

Thanks,
 Zsaga

### CODE REVIEW

**Comment by blzaugg** [comment]
@peterborkuti ,

After your fix, the Datatable demo no longer works.
http://localhost/alloy-ui/3.0.x/demos/datatable/

I'd also like you to create a unit test, to ensure your use-case (and variations) is covered.
http://localhost/alloy-ui/3.0.x/src/aui-datatable/tests/unit/

**Comment by peterborkuti** [comment]
@blzaugg, @zsagia 

Hi Byran,

I do not know, on which branch you tested it, but on AUI  master, it definitely works.

See the attached anim-gif:

aui1953-test-aui-master

**Comment by peterborkuti** [comment]
I also tested datatable on master-deprecated:

aui1953-test-aui-master-deprecated

About the unit-test: I was thinking of wiriting one, but as I checked the code, there was commit, which states:

AUI-1288 We should add proper tests for our components, not specific to a bug ticket. Tests should cover the component behavior instead.
6dc19e321a4371db254392eddcdd0bb492ad8ba5

And it deleted a unit test specifically written for a bug, so I thought, that this is a convention.

**Comment by blzaugg** [comment]
I test it again to be sure.

I was not aware of 6dc19e3.

Talking to @jonmak08 , we still need to cover your use-case, as you're adding/extending the pattern to define cell data. Even if it's to address a bug.

So either:
- an existing test needs to be extended, to cover your use-case,
- or if one can't be, your use-case is a valid case on it's own, and should be added.

**Comment by blzaugg** [comment]
I must have done something to the demo to break it sorry.

**Comment by blzaugg** [comment]
item auto selection

There is a bug where matching Names get selected/highlighted when editing the cell value.

**Comment by blzaugg** [comment]
I'm confused/unsure how I'd create an Array version for `DropDownCellEditor` `options`.

Object Version:
```js
{
    key: 'fruit',
    sortable: true,
    editor: new Y.DropDownCellEditor({
        editable: true,
        multiple: true,
        options: {
            apple: 'Apple',
            cherry: 'Cherry',
            banana: 'Banana',
            kiwi: 'Kiwi'
        }
    })
},
```

Array Version: (this doesn't work)
```js
{
    key: 'fruit',
    sortable: true,
    editor: new Y.DropDownCellEditor({
        editable: true,
        multiple: true,
        options: [
            {apple: 'Apple'},
            {cherry: 'Cherry'},
            {banana: 'Banana'},
            {kiwi: 'Kiwi'}
        ]
    })
},
```

**Comment by peterborkuti** [comment]
Here is my plan to "array of complex objects" option:

options: [
 {'label': 'Apple', 'value': 'apple'},
 {'label': 'Cherry', 'value': 'cherry'}
]

The simple array option:
options: [ 'Apple', 'Cherry'];

**Comment by peterborkuti** [comment]
"There is a bug where matching Names get selected/highlighted when selecting the cell value"

I am not sure about, that this is a bug. Rather this is the way, how is it working.
I checked it and noticed it, but I thought, it is OK.
When end-user selects something, maybe it is not a bad thing to show the same-value options.

But I understand your concerns. Should I fix it?

To tell you the truth, we were interesting in your overall thoughts about this fix. If it seems to you to be a good direction, I should care about tuning Liferay also and making the backports also, because that could be tricky.

**Comment by blzaugg** [comment]
Since I typed up a whole long comment, only to have it lost when Chrome crashed. I'll email you.

**Comment by peterborkuti** [comment]
Hi,

I checked metal.js's select: https://github.com/metal/steel-select

It works very similar to my proposal. It gets default options like this:

```
window.select4 = new steel.Select({
			items: [
                {name: 'Apple', value:'apple'},
                {name: 'Cherry', value:'cherry'},
                {name: 'Grape', value:'grape'},
                {name: 'Grape', value:'grape'},
                {name: 'Grape', value:'grape'},
                {name: 'Grape', value:'grape'}
            ],
			buttonClass: 'btn btn-default btn-sm dropdown-select-group-right'
		}).render('#fourth');
```
And it accepts and deals with same name-value pairs well.

**Comment by blzaugg** [comment]
If you'd like to take inspiration/confirmation from Metal.js, to solve this issue in AUI master (Portal master), that is fine. It needs to be thoroughly tested for edge cases, as we'd be introducing a different internal data format and an additional external input format. Both existing and this new external input format would need to be supported.

One note @jonmak08 made was, this may allow us to transition to Metal.js more easily, as the new external input format would match.

But for AUI 2.0.x (Portal ee-6.2.x), we'd like to stick to the current internal data format and external input format, to minimize API changes and regressions.

**Pull request closed without merging**
